---
- name: Deploy Flask app with virtualenv
  hosts: web
  become: true

  vars:
    app_dir: /home/ubuntu/flask-app
    venv_dir: /home/ubuntu/flask-venv

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Python3, pip, and virtualenv
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv

    - name: Create target app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Copy Flask app to server
      copy:
        src: flask-app/
        dest: "{{ app_dir }}"
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create virtual environment
      command: python3 -m venv "{{ venv_dir }}"
      args:
        creates: "{{ venv_dir }}"

    - name: Install requirements in virtualenv
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ venv_dir }}"

    - name: Start Flask app in background
      shell: |
        source {{ venv_dir }}/bin/activate
        nohup python3 {{ app_dir }}/app.py > flask.log 2>&1 &
      args:
        chdir: "{{ app_dir }}"
